ci:
  autoupdate_commit_msg: "MAINT: autoupdate pre-commit hooks"
  autoupdate_schedule: quarterly

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            .*\.svg
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types_or:
          - c++
          - c
          - cuda

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.23.2
    hooks:
      - id: latexindent
        args:
          - "-y=defaultIndent: '  '"

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
      - id: nbqa-isort

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.id
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
