
[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
    "ampform",
    "sympy",
]
name = "gluex-amplitude"
requires-python = ">=3.7"
version = "0.0.0"

[project.optional-dependencies]
dev = [
    "gluex-amplitude[jupyter]",
    "gluex-amplitude[sty]",
]
jupyter = [
    "ipywidgets",
    "jupyterlab",
    "jupyterlab-code-formatter",
]
sty = [
    "black",
    "isort",
    "pre-commit",
]

[tool.isort]
known_third_party = "THIRDPARTY,sympy"
profile = "black"
