[project]
name = "gluex-amplitude"
version = "0.0.0"
description = "Investigation of symbolic amplitude models for the GlueX experiment"
requires-python = "~=3.13.0"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
dependencies = [
    "numpy",
    "pandas",
    "uproot",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[dependency-groups]
dev = [
    "ruff",
    "sphinx-autobuild",
    { include-group = "doc" },
    { include-group = "jupyter" },
    { include-group = "notebooks" },
]
doc = [
    "myst-nb",
    "sphinx",
    "sphinx-api-relink",
    "sphinx-book-theme",
    "sphinx-codeautolink[ipython]",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-togglebutton",
]
jupyter = [
    "jupyter-ruff",
    "jupyterlab",
    "jupyterlab-git",
    "jupyterlab-lsp",
    "jupyterlab-myst",
    "jupyterlab-quickopen",
    "jupyterlite-core",
    "jupyterlite-pyodide-kernel",
]
notebooks = [
    "ampform",
    "ipympl",
    "ipywidgets",
    "matplotlib",
    "sympy",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.compwa.policy]
package-manager = "pixi"
repo-name = "gluex-amplitude"

[tool.compwa.policy.nb]
excluded-dependencies = [
    "python-lsp-ruff",
    "python-lsp-server",
]
no-binder = true

[tool.compwa.policy.github]
no-cd = true
no-pypi = true

[tool.pixi.dependencies]
clang = "*"
make = "*"
python = "3.13.*"
root = "*"

[tool.pixi.environments]
default = { features = ["dev"], solve-group = "main" }

[tool.pixi.pypi-dependencies]
gluex-amplitude = { path = ".", editable = true }

[tool.pixi.tasks.all]
depends-on = [
    "build",
    "doc",
    "linkcheck",
    "lite",
    "style",
]
description = "Run all continuous integration (CI) tasks locally"

[tool.pixi.tasks.build]
cmd = "make CXX=clang CXXFLAGS='-std=c++20 -O3 -Wno-' SHELL=/bin/bash"
description = "Build C++ project"

[tool.pixi.tasks.doc]
cmd = """
sphinx-build \
    --builder=html \
    --fail-on-warning \
    --keep-going \
    --show-traceback \
    docs/ \
    docs/_build/html/
"""
depends-on = "lite"
description = "Build website"
env = { EXECUTE_NB = "yes" }

[tool.pixi.tasks.doclive]
cmd = """
sphinx-autobuild \
    --builder=html \
    --open-browser \
    --port=0 \
    --re-ignore='/_build(/.*)?$' \
    --re-ignore='/\\.cache(/.*)?$' \
    --re-ignore='/\\.egg-info(/.*)?$' \
    --re-ignore='/\\.ipynb_checkpoints(/.*)?$' \
    --re-ignore='/\\.virtual_documents(/.*)?$' \
    --re-ignore='/docs$' \
    --re-ignore='\\.egg-info(/.*)?$' \
    --re-ignore='\\.gif$' \
    --re-ignore='\\.pickle$' \
    --re-ignore='\\.png$' \
    --re-ignore='\\.svg$' \
    docs/ \
    docs/_build/html/
"""
description = "Set up a server to directly preview changes to the HTML pages"

[tool.pixi.tasks.docnblive]
cmd = "pixi run doclive"
description = "Set up a server to directly preview changes to the HTML pages with cached notebook execution"
env = { EXECUTE_NB = "yes" }

[tool.pixi.tasks.lab]
args = [{ "arg" = "paths", "default" = "" }]
cmd = "jupyter lab {{ paths }}"
description = "Run Jupyter Lab"

[tool.pixi.tasks.linkcheck]
cmd = """
sphinx-build \
    --builder=linkcheck \
    --show-traceback \
    docs/ \
    docs/_build/linkcheck/
"""
description = "Check external links in the documentation (requires internet connection)"

[tool.pixi.tasks.lite]
cmd = """
jupyter lite build \
    --contents feynman-gluex-two-pseudoscalar.svg \
    --contents widget.ipynb \
    --ignore-contents=_build \
    --output-dir lite
"""
cwd = "docs"
description = "Build Jupyter Lite server"

[tool.pixi.tasks.style]
cmd = "pre-commit run --all-files"
description = "Perform all linting, formatting, and spelling checks"

[tool.pixi.tasks.upgrade]
depends-on = [
    "_upgrade-pixi",
    "_upgrade-precommit",
]
description = "Upgrade all lock files"

[tool.pixi.tasks._upgrade-pixi]
cmd = "pixi update"

[tool.pixi.tasks._upgrade-precommit]
cmd = "pre-commit autoupdate -j8"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-64",
    "osx-arm64",
]

[tool.ruff]
extend-include = ["*.ipynb"]
preview = true
show-fixes = true
src = ["src"]

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"

[tool.ruff.lint]
ignore = [
    "ANN401",
    "COM812",
    "CPY001",
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D213",
    "D407",
    "D416",
    "DOC",
    "E501",
    "FURB101",
    "FURB103",
    "FURB140",
    "G004",
    "ISC001",
    "PLW1514",
    "PT001",
    "PTH",
    "RUF067",
    "SIM108",
]
select = ["ALL"]
task-tags = ["cspell"]

[tool.ruff.lint.flake8-builtins]
ignorelist = ["display"]

[tool.ruff.lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[tool.ruff.lint.flake8-self]
ignore-names = [
    "_global_settings",
    "_latex",
    "_print",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "ANN",
    "B018",
    "C408",
    "C90",
    "D",
    "E303",
    "E703",
    "E741",
    "N803",
    "N806",
    "N816",
    "PLR09",
    "PLR2004",
    "PLW0602",
    "PLW0603",
    "RUF001",
    "S101",
    "T20",
    "TC00",
]
"**/widget.ipynb" = ["ARG001", "ARG002", "S307"]
"docs/*" = ["INP001", "S101", "S113"]
"docs/conf.py" = ["A001", "D100"]
"script/*" = ["D100", "INP001"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.tombi.format.rules]
indent-width = 4
line-width = 88

[tool.tombi.lint.rules]
key-empty = "off"

[[tool.tombi.schemas]]
root = "tool.compwa.policy"
path = "https://raw.githubusercontent.com/ComPWA/policy/0.9.1/compwa-policy.schema.json"
include = ["pyproject.toml"]
