#!/bin/bash
set -ex
curl -LsSf https://pixi.sh/install.sh | bash
export PATH="$HOME/.pixi/bin:$PATH"

pixi_packages="$(NO_COLOR= pixi list --explicit | awk 'NR > 1 {print $1}')"
if [[ -n "$pixi_packages" ]]; then
  pixi global install $pixi_packages
fi
pixi clean cache --yes
