title: GlueX amplitude model
author: GlueX PWA team
copyright: "2023"

execute:
  allow_errors: false
  execute_notebooks: cache
  timeout: 600

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
  notebook_interface: jupyterlab

only_build_toc_files: true

repository:
  url: https://github.com/redeboer/gluex-amplitude
  path_to_book: docs
  branch: main

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    myst_heading_anchors: 3
    nb_execution_show_tb: True
