name: C++

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIXI_COLOR: always
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.cc"
      - "**/*.cfg"
      - "**/*.h"
      - "**/Makefile"
      - .github/workflows/amptools.yml
  workflow_dispatch:

jobs:
  build:
    name: Build and execute
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: binaries-${{ matrix.os }}-${{ hashFiles('**/*.cc', '**/*.h', 'extern/AmpTools', '**/Makefile*') }}
          path: |
            **/*.a
            **/*.d
            **/*.o
            **/compiler_flags
            **/bin
            **/lib
      - uses: prefix-dev/setup-pixi@9dabb60412d3d2d967a8d682f7ce01317af40514 # v0.11.0
        with:
          activate-environment: true
          cache: true
      - if: startsWith(matrix.os, 'macos')
        run: pixi run build -j$(sysctl -n hw.ncpu)
      - if: startsWith(matrix.os, 'ubuntu')
        run: pixi run build -j$(nproc)
      - name: Run executables
        run: |
          ./print_amplitudes -c zlm.cfg > .print_amplitudes.log
          python makeComparison.py
          ./draw_zlm
        working-directory: script
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        if: always()
        with:
          name: cpp-logs-${{ matrix.os }}
          path: |
            script/**.log
            script/**.root
            !script/data.root
