name: C++

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    env:
      ROOT_VERSION: v6.28.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install g++
      - uses: actions/cache@v3
        with:
          key: root-${{ env.ROOT_VERSION }}
          path: ./root
      - name: Install ROOT
        run: |
          if [[ ! -d root ]]; then
            tar_file=root_$ROOT_VERSION.Linux-ubuntu22-x86_64-gcc11.3.tar.gz
            wget https://root.cern/download/$tar_file -q
            tar xzf $tar_file
          fi
      - run: |
          sudo rm /bin/sh
          sudo ln -s /bin/bash /bin/sh
          source ./root/bin/thisroot.sh
          pushd extern/AmpTools
          make
          popd
      - run: make
