name: CI

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cpp:
    name: Build AmpTools and GlueXAmplitude libraries
    runs-on: ubuntu-22.04
    env:
      ROOT_VERSION: v6.28.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt install g++
      - uses: actions/cache@v3
        with:
          key: root-${{ env.ROOT_VERSION }}
          path: ./root
      - name: Install ROOT
        run: |
          if [[ ! -d root ]]; then
            tar_file=root_$ROOT_VERSION.Linux-ubuntu22-x86_64-gcc11.3.tar.gz
            wget https://root.cern/download/$tar_file -q
            tar xzf $tar_file
          fi
      - run: |
          source ./root/bin/thisroot.sh
          pushd extern/AmpTools
          make
          popd
        shell: bash
      - run: make

  doc:
    name: Execute and build documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ComPWA/actions/pip-install@v1
        with:
          extras: doc
          python-version: "3.10"
      - run: jupyter book build docs -W
      - uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          path: docs/_build/html

  gh-pages:
    name: Upload to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs:
      - doc
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
