name: Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - pyproject.toml
  workflow_dispatch:

jobs:
  doc:
    name: Execute and build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: True
      - run: >-
          uv run --extra doc \
            jupyter book build docs --warningiserror
      - uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: docs/_build/html

  gh-pages:
    name: Upload to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs:
      - doc
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
